server:
  ip: localhost
  port: 9090


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hl?serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
#  #输出sql语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    staticAccessPath: /public/**
    path: D:/projectMenu/java/springboot/src/main/resources/static/public/
